# Generated by Django 4.0.8 on 2022-10-10 12:26
from __future__ import annotations

import datetime

import django.db.models.deletion
from django.db import migrations
from django.db import models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="by_user",
                to="api.hnuser",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="dead",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="item",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="item",
            name="time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2022, 10, 10, 12, 26, 19, 556658, tzinfo=utc
                ),
                null=True,
            ),
        ),
    ]
